name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: CI/CD
    runs-on: mramra
    steps:
    - uses: action/checkout@v2
    - name: Build the Docker image
      run: docker build . CI-CD/Dockerfile -t ci-cd
    
