name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: CI/CD
    runs-on: self-hosted
    steps:
    - uses: action/checkout@v1
    - name: Build the Docker image
      run: docker build . CI-CD/Dockerfile -t ci-cd
    
